# Generated by Django 4.2.7 on 2023-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Debugear', max_length=100)),
                ('rubro', models.CharField(default='Test', max_length=100)),
                ('fecha_habilitacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'coding_task',
            },
        ),
    ]
